### ISSUE TITLE
Sidebar hierarchical structure for theme bigpicture

### ISSUE THREAD

**Issue by gschlafly** [learning-unlimited/ESP-Website#3595]
#### Description
It would be great if the sidebar worked like the sidebar of readthedocs.com. For example, see [qtile](http://docs.qtile.org/en/latest/manual/ref/commands.html#qtile). When a node is not selected, it should be collapsed. For example, the `Recources` button would not be visible in the screenshot below. The button shapes and typography may need adjustment too to convey the hierarchical structure well. Moreover, it would be nice if there were a `Next` button at the bottom right of each page, taking you to the next node in the hierarchical structure.

#### Screenshots
![image](https://user-images.githubusercontent.com/23206511/212502365-f031d8a5-d889-4ceb-ad14-9f97670e12bb.png)

**Comment by willgearty** [comment]
Thanks for the issue @gschlafly! Quick question about the preferred behavior here. Would the highest "nodes" (e.g., "TEACH") also be links? Or would they only serve as clickable objects that then expand to show the actual link options (e.g., "Portal Droplet 2022" and "Resources")?

**Comment by gschlafly** [comment]
The highest nodes would also be links!

**Comment by gschlafly** [comment]
Anthony, from the Berkeley Splash, may also have some comments about this feature! @Saccharine-Coal

**Comment by dykChirag** [comment]
Hi @hwatheod @willgearty , could you please assign this to me ?

**Comment by willgearty** [comment]
@chirag-patil625 Thanks for your interest in contributing to our project! I've assigned you to this issue. Please make sure to check out our [instructions for getting started](https://github.com/learning-unlimited/ESP-Website/wiki#getting-started) and follow our [contribution rules](https://github.com/learning-unlimited/ESP-Website/wiki#rules). Let me know if you have any questions.

**Comment by dishantdabithegreat** [comment]
# Issue #3595: Accordion-Style Hierarchical Sidebar - CSS Only Implementation

## Overview
This document shows ONLY the CSS changes for implementing an accordion-style hierarchical sidebar in ESP-Website. Uses native HTML5 elements - no JavaScript, no Django templates needed!

---

## CSS File to Modify

### File Location
```
esp/public/media/default_styles/main.css
```

---

## CSS Changes

### OLD CODE (Current):
```css
.divsecondarynavlink {
  font-family: Arial, Lucida, Helvetica, sans-serif;
  color: #FFFFFF;
  line-height: 133%;
  list-style: none;
  margin: 0px;
}
```

---

### NEW CODE (Add at end of main.css):
```css
/* ============================================
   ACCORDION SIDEBAR STYLES - Issue #3595
   Uses native HTML5 <details> and <summary>
   No JavaScript required!
   ============================================ */

/* Sidebar navigation container */
#submenu {
    padding-left: 0;
    list-style: none;
}

/* Style for the collapsible section header */
#submenu details > summary {
    list-style: none;
    cursor: pointer;
    padding: 12px 15px;
    background-color: #141414;
    color: #FFFFFF;
    font-weight: bold;
    border-bottom: 1px solid #497CCA;
    font-family: Arial, Lucida, Helvetica, sans-serif;
    line-height: 133%;
}

/* Hide default marker in WebKit browsers */
#submenu details > summary::-webkit-details-marker {
    display: none;
}

/* Add custom chevron using ::before */
#submenu details > summary::before {
    content: "▸";
    margin-right: 10px;
    display: inline-block;
    transition: transform 0.3s ease;
    font-size: 12px;
}

/* Rotate chevron when open */
#submenu details[open] > summary::before {
    transform: rotate(90deg);
}

/* Hover state for headers */
#submenu details > summary:hover {
    background-color: #497CCA;
    color: #FFFFFF;
}

/* Submenu items container */
#submenu details > .sidebar-submenu {
    list-style: none;
    padding: 0;
    margin: 0;
    background-color: #1a1a1a;
}

/* Individual submenu items */
#submenu details > .sidebar-submenu li {
    padding: 8px 15px 8px 35px;
    font-family: Arial, Lucida, Helvetica, sans-serif;
    color: #BCCAF5;
    line-height: 133%;
}

/* Links in submenu */
#submenu details > .sidebar-submenu li a {
    color: #BCCAF5;
    text-decoration: none;
}

#submenu details > .sidebar-submenu li a:hover {
    color: #497CCA;
    text-decoration: underline;
}

/* Indentation for nested items */
#submenu .indent {
    padding-left: 30px;
}

/* Active state styling */
#submenu li.active {
    background-color: #497CCA;
    color: #FFFFFF;
}

#submenu li.active a {
    color: #FFFFFF;
}

/* Smooth open animation */
#submenu details > .sidebar-submenu {
    animation: slideDown 0.3s ease;
}

@keyframes slideDown {
    from {
        opacity: 0;
        transform: translateY(-10px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}
```

---

## Summary

| Item | Details |
|------|---------|
| **File to Modify** | `esp/public/media/default_styles/main.css` |
| **Lines to Add** | ~70 lines at end of file |
| **Technology** | Pure CSS + HTML5 `<details>` and `<summary>` |
| **No JavaScript** | ✅ Browser handles accordion behavior |
| **No Django** | ✅ Only CSS changes needed |

---

## How It Works

1. **HTML5 `<details>` element** - Creates collapsible widget
2. **HTML5 `<summary>` element** - Clickable header
3. **CSS `::before` pseudo-element** - Shows chevron triangle (▸)
4. **CSS `transform: rotate(90deg)`** - Rotates chevron when open
5. **CSS `@keyframes`** - Smooth slide animation

---

## Browser Support

| Browser | Version |
|---------|---------|
| Chrome | 12+ |
| Firefox | 49+ |
| Edge | 79+ |
| Safari | 6+ |
| Opera | 15+ |

---

## Testing Checklist

- [ ] Click on section header toggles submenu
- [ ] Chevron rotates when opened/closed
- [ ] Smooth animation plays
- [ ] Hover state works on headers
- [ ] Links in submenu work correctly

---

## Related Issue
- Issue #3595: Accordion-style hierarchical sidebar similar to ReadTheDocs
